apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-exporter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yijun-l/wiki-config.git
    targetRevision: main
    path: infra/kafka-exporter

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - Prune=true