apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: hive
        - name: POSTGRES_PASSWORD
          value: hive123
        - name: POSTGRES_DB
          value: hive_metastore
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
