apiVersion: v1
kind: Pod
metadata:
  name: spark-client
  namespace: test
spec:
  serviceAccountName: spark
  containers:
    - name: spark-tools
      image: apache/spark:latest
      command: ["/bin/sh", "-c", "sleep infinity"]