apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-entrypoint
  namespace: hive
data:
  entrypoint.sh: |-
    #!/bin/bash
    export HADOOP_VERSION=3.3.1
    export METASTORE_VERSION=3.1.2
    export AWS_SDK_VERSION=1.11.901
    export LOG4J_VERSION=2.8.2
    export JAVA_HOME=/usr/local/openjdk-8
    export HADOOP_HOME=/opt/hadoop-${HADOOP_VERSION}
    export HADOOP_CLASSPATH=${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar:${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar:${HIVE_HOME}/lib/log4j-core-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-api-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-1.2-api-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-slf4j-impl-${LOG4J_VERSION}.jar
    export HIVE_HOME=/opt/apache-hive-metastore-${METASTORE_VERSION}-bin
    ${HIVE_HOME}/bin/schematool -initSchema -dbType postgres
    ${HIVE_HOME}/bin/start-metastore
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore
  namespace: hive
data:
  metastore-site.xml: |-
    <configuration>
        <property><name>metastore.task.threads.always</name><value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value></property>
        <property><name>metastore.expression.proxy</name><value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value></property>
        <property><name>metastore.storage.schema.reader.impl</name><value>org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader</value></property>
        <property><name>fs.defaultFS</name><value>s3a://hive-warehouse</value></property>
        <property><name>fs.s3a.access.key</name><value>minioadmin</value></property>
        <property><name>fs.s3a.connection.ssl.enabled</name><value>false</value></property>
        <property><name>fs.s3a.endpoint</name><value>http://minio:9000</value></property>
        <property><name>fs.s3a.impl</name><value>org.apache.hadoop.fs.s3a.S3AFileSystem</value></property>
        <property><name>fs.s3a.path.style.access</name><value>true</value></property>
        <property><name>fs.s3a.secret.key</name><value>minio123</value></property>
        <property><name>hive.metastore.uris</name><value>thrift://hive-metastore:9083</value></property>
        <property><name>javax.jdo.option.ConnectionDriverName</name><value>org.postgresql.Driver</value></property>
        <property><name>javax.jdo.option.ConnectionPassword</name><value>hive123</value></property>
        <property><name>javax.jdo.option.ConnectionURL</name><value>jdbc:postgresql://postgres:5432/hive_metastore</value></property>
        <property><name>javax.jdo.option.ConnectionUserName</name><value>hive</value></property>
    </configuration>
