apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive
spec:
  ports:
    - name: thrift
      port: 9083
  selector:
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: hive-metastore
