apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      hostAliases:
        - ip: "72.32.157.228"
          hostnames:
            - "jdbc.postgresql.org"
      containers:
        - name: metastore
          image: apache/hive:4.1.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              wget --no-check-certificate -O /tmp/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar
              /entrypoint.sh

          env:
            - name: SERVICE_NAME
              value: "metastore"
            - name: DB_DRIVER
              value: "postgres"
            - name: HIVE_AUX_JARS_PATH
              value: "/tmp"
            - name: SERVICE_OPTS
              value: >-
                -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/hive_metastore
                -Djavax.jdo.option.ConnectionUserName=hive
                -Djavax.jdo.option.ConnectionPassword=hive123
                -Dfs.s3a.endpoint=http://minio:9000
                -Dfs.s3a.access.key=minioadmin
                -Dfs.s3a.secret.key=minio123
                -Dfs.s3a.path.style.access=true
                -Dhive.metastore.warehouse.dir=s3a://hive-warehouse/
          ports:
            - containerPort: 9083
