apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
  namespace: hive
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hive-metastore
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: hive-metastore
  serviceName: hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hive-metastore
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: hive-metastore
    spec:
      initContainers:
        - name: init-wait-db
          image: busybox:latest
          command: ["/bin/sh","-c"]
          args: ["until nc -z -v -w90 postgres 5432; do echo Waiting for DB...; sleep 5; done"]
      containers:
        - name: metastore
          image: rtdl/hive-metastore:3.1.2
          command: [bash, entrypoint/entrypoint.sh]
          ports:
            - containerPort: 9083
              name: thrift
          volumeMounts:
            - name: hive-config
              mountPath: /opt/apache-hive-metastore-3.1.2-bin/conf
            - name: entrypoint
              mountPath: /opt/entrypoint
      volumes:
        - name: hive-config
          configMap:
            name: hive-metastore
        - name: entrypoint
          configMap:
            name: hive-metastore-entrypoint
