apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yijun-l/wiki-config.git
    targetRevision: main
    path: infra/hive
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: hive

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true