# wiki-config/environments/dev/service-override.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wiki-service
          image: docker.io/yijunl/wiki-service:dev-latest