# environments/dev/values.yaml
replicaCount: 1

image:
  repository: docker.io/yijunl/wiki-service
  tag: 4ff52f1210d6301b591c0f788b82869a3ad0485b
  pullPolicy: Always

service:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: debug
      port: 5005
      targetPort: 5005
      nodePort: 30505

resources: {}