# environments/dev/values.yaml
replicaCount: 1

image:
  repository: docker.io/yijunl/wiki-service
  tag: 07e526334da5127b5396aed7dc5da2a759ae4bc4
  pullPolicy: Always

service:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: debug
      port: 5005
      targetPort: 5005
      nodePort: 30505

resources: {}