# environments/dev/values.yaml
replicaCount: 1

image:
  repository: docker.io/yijunl/wiki-service
  tag: e18736ea40621e27bfa087b4d408ff93bf9125e2
  pullPolicy: Always

service:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: debug
      port: 5005
      targetPort: 5005
      nodePort: 30505

resources: {}